// src/components/core/Layout.tsx
import React, { FC } from 'react'
import Navigation from './Navigation'
import Header from './Header'
import { useDispatch, useSelector } from 'react-redux'
import { SetWallet } from '../../store/actions/wallet.actions'
import { SetChain } from '../../store/actions/chain.actions'
import { wEthereum } from '../../utils/windowUtil'
import Web3Wallet from '../../support/web3/wallet'
import web3Utils from 'web3-utils'
import { WEB3_WALLET } from '../../constant'

interface Props {
  children: React.ReactNode | string
}

const Layout: FC<Props> = ({ children }) => {
  let pollChainTimeObj:any = null
  let pollAccountAddressTimeObj:any = null
  const web3 = useSelector((state:any) => state.web3)
  const account = useSelector((state:any) => state.account)
  const dispatch = useDispatch()

  const pollWeb3WalletNetwork = () => {
    if (!web3.eth) {
      throw new Error('web3 not found')
    }
    if (!web3.eth.net || typeof web3.eth.net.getId !== 'function') {
      return
    }

    pollChainTimeObj = setInterval(() => {
      web3.eth.net.getId().then((id:string) => {
        dispatch(SetChain(id))
        clearInterval(pollChainTimeObj)
      }).catch((e:any) => {
        throw e
      })
    }, 500)
  }

  const pollWeb3WalletAccountAddress = () => {
    pollAccountAddressTimeObj = setInterval(() => {
      if (!web3.eth) {
        throw new Error('web3 not found')
        // clearInterval(pollAccountAddressTimeObj)
      }
      // 获取到账户
      web3.eth.getAccounts((err:string, accounts:string[]) => {
        if (err) {
          throw new Error('Get accounts error' + err)
          // clearInterval(pollAccountAddressTimeObj)
        }
        if (!accounts.length) {
          throw new Error('Please make sure that your Web3 Wallet is unlocked')
          // clearInterval(pollAccountAddressTimeObj)
        }
        const address = accounts[0]
        if (account.address !== null && address.toLowerCase() !== account.address.toLowerCase()) {
          // 钱包对象
          console.log(2222)

          dispatch(SetWallet(new Web3Wallet(address)))
          clearInterval(pollAccountAddressTimeObj)
        }
      })
    }, 500)
  }

  const checkWeb3WalletAccountAddressChange = () => {
    wEthereum.on('accountsChanged', (account:string[]) => {
      if (account.length > 0) {
        dispatch(SetWallet(new Web3Wallet(account[0])))
      }
    })
  }

  const checkWeb3WalletNetwork = () => {
    web3.eth.net.getId().then((id:string) => {
      dispatch(SetChain(id))
    })
    wEthereum.on('networkChanged', (id:string) => {
      dispatch(SetChain(id))
    })
  }
  const afterConnectWallet = () => {
    // web3Utils._.debounce(function() {
    clearIntervals()
    if (account.address !== null && account.identifier === WEB3_WALLET) {
      if (wEthereum.isMetaMask) {
        checkWeb3WalletAccountAddressChange()
        checkWeb3WalletNetwork()
      } else {
        pollWeb3WalletNetwork()
        pollWeb3WalletAccountAddress()
      }
    }
    // })
  }
  const clearIntervals = () => {
    clearInterval(pollChainTimeObj)
    clearInterval(pollAccountAddressTimeObj)
  }
  return (
    <div>
      <Navigation />
      <Header afterConnectWallet={afterConnectWallet} />
      {children}
    </div>
  )
}

export default Layout

// src/components/layout/Index.vue
<template>
  <div>
    <div class='router'>
      <ul>
        <li v-for=' route in routes' :key='route.name'>
          <router-link :to='route.path'>{{ route.name }}</router-link>
        </li>
      </ul>
    </div>
    <i-header
      class='header'
      :afterConnectWallet='afterConnectWallet'
    />
    <div class='content'>
      <router-view />
    </div>
    <i-footer class='footer' />
  </div>
</template>

<script>
import router from '@/router'
import IHeader from './Header'
import IFooter from './Footer'
import web3Utils from 'web3-utils'
import Web3Wallet from '@/components/web3/wallet'
import { mapActions, mapState } from 'vuex'
import { WEB3_WALLET } from '@/constant'


export default {
  data() {
    return {
      pollChainTimeObj: null,
      pollAccountAddressTimeObj: null,
      routes: []
    }
  },
  components: {
    IHeader,
    IFooter

  },
  props: {},
  computed: {
    ...mapState('main', [
      'currentChain',
      'account',
      'web3',
      'wallet'
    ])
  },
  watch: {},
  created() {
  },
  mounted() {
    //
    this.routes = router.getRoutes()
    //
    this.setupOnlineEnvironment()
  },
  methods: {

    ...mapActions('main', [
      'changeChain',
      'setWallet',
      'setAccountBalance'
    ]),

    setupOnlineEnvironment: web3Utils._.debounce(function() {
      const that = this
      that.clearIntervals()
      //
      if (that.account.address !== null && that.account.identifier === WEB3_WALLET) {
        if (window.ethereum.isMetaMask) {
          that.checkWeb3WalletAccountAddressChange()
          that.checkWeb3WalletNetwork()
        } else {
          that.pollWeb3WalletNetwork()
          that.pollWeb3WalletAccountAddress()
        }
      }
    }),

    //清理轮询
    clearIntervals() {
      clearInterval(this.pollChainTimeObj)
      clearInterval(this.pollAccountAddressTimeObj)
    },

    pollWeb3WalletNetwork() {
      const that = this
      if (!that.web3.eth) {
        throw new Error('web3 not found')
      }
      if (!that.web3.eth.net || typeof that.web3.eth.net.getId !== 'function') {
        return
      }
      that.pollChainTimeObj = setInterval(() => {
        that.web3.eth.net.getId().then(id => {
          that.changeChain(id)
          clearInterval(that.pollChainTimeObj)
        }).catch(e => {
          throw e
        })
      }, 500)
    },

    pollWeb3WalletAccountAddress() {
      const that = this
      //
      that.pollAccountAddressTimeObj = setInterval(() => {
        if (!that.web3.eth) {
          throw new Error('web3 not found')
          //
          clearInterval(this.pollAccountAddressTimeObj)
        }
        //获取到账户
        that.web3.eth.getAccounts((err, accounts) => {
          if (err) {
            throw new Error('Get accounts error' + err)
            clearInterval(that.pollAccountAddressTimeObj)
          }
          if (!accounts.length) {
            throw new Error('Please make sure that your Web3 Wallet is unlocked')
            clearInterval(that.pollAccountAddressTimeObj)
          }
          const address = accounts[0]
          if (that.account.address !== null && address.toLowerCase() !== that.account.address.toLowerCase()) {
            //钱包对象
            this.setWallet(new Web3Wallet(address))
            clearInterval(that.pollAccountAddressTimeObj)
          }
        })
      }, 500)
    },

    checkWeb3WalletAccountAddressChange() {
      const that = this
      try {
        window.ethereum.on('accountsChanged', account => {
          if (account.length > 0) {
            that.setWallet(new Web3Wallet(account[0]))
          }
        })
      } catch (e) {
        throw e
      }
    },

    checkWeb3WalletNetwork() {
      const that = this
      that.web3.eth.net.getId().then(id => {
        that.changeChain(id)
      })
      window.ethereum.on('networkChanged', id => {
        that.changeChain(id)
      })
    },

    afterConnectWallet() {
      this.setupOnlineEnvironment()
    }

  }
}
</script>
<style lang='scss' scoped>
.router {
  display: flex;
  justify-content: flex-start;

  ul {
    li {
      list-style: none;
    }
  }
}

.header {
  padding: 30px;
  margin-top: 10px;
  border: black solid 1px;
}

.content {
  padding: 30px;
  margin-top: 10px;
  border: black solid 1px;
}

.footer {
  padding: 30px;
  margin-top: 10px;
  border: black solid 1px;
}
</style>
